spring:
  datasource:
      url: jdbc:mysql://localhost:3306/renkeyu?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: renkeyu
      password: renkeyu
mybatis:
   mapperLocations: classpath:/mapper/*.xml

server:
  port: 18081
